#image: docker:stable
variables:
  KUBECTL: v1.17.0
  KIND: v0.8.1
#services:
#  - docker:dind
stages:
  - test
test:
  stage: test
  script:
    - apt update
    - apt install -y wget curl
    - wget -O /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND}/kind-linux-amd64
    - chmod +x /usr/local/bin/kind
    - wget -O /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL}/bin/linux/amd64/kubectl
    - chmod +x /usr/local/bin/kubectl
    - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    - chmod 700 get_helm.sh
    - ./get_helm.sh
    - mkdir $HOME/.kube/
    - cp ./config $HOME/.kube/config
    - kubectl config get-contexts
    - kubectl config use-context kind-kind
    - kubectl get pods --all-namespaces
    - helm -n poc-configmap-secret upgrade poc-configmap-secret k8s/charts/poc-configmap-secret/ --values k8s/charts/poc-configmap-secret/values.yaml