namespace:
  name: poc-configmap-secret
image:
  name: localhost:5000/poc-configmap-secret
  tag: latest
service:
  port: 80
  targetPort: 8080
  nodePort: 30000
volume:
  configmap:
    name: poc-configmap-volume
    path: /config/configmap
  secret:
    name: poc-secret-volume
    path: /config/secret
configmap:
  name: poc-configmap
secret:
  name: poc-secret
